#ifndef __SX_1276_H
#define __SX_1276_H

// Registers Map
#define RegFifo                        ((__uint8_t)0x00) // r/w register
#define RegOpMode                      ((__uint8_t)0x01)
#define RegBitrateMsb                  ((__uint8_t)0x02)
#define RegBitrateLsb                  ((__uint8_t)0x03)
#define RegFdevMsb                     ((__uint8_t)0x04)
#define RegFdevLsb                     ((__uint8_t)0x05)
#define RegFrfMsb                      ((__uint8_t)0x06)
#define RegFrfMid                      ((__uint8_t)0x07)
#define RegFrfLsb                      ((__uint8_t)0x08)
#define RegPaConfig                    ((__uint8_t)0x09)
#define RegPaRamp                      ((__uint8_t)0x0A)
#define RegOcp                         ((__uint8_t)0x0B)
#define RegLna                         ((__uint8_t)0x0C)
#define RegFifoAddrPtr                 ((__uint8_t)0x0D)
#define RegFifoTxBaseAddr              ((__uint8_t)0x0E)
#define RegFifoRxBaseAddr              ((__uint8_t)0x0F)
#define FifoRxCurrentAddr              ((__uint8_t)0x10)
#define RegIrqFlagsMask                ((__uint8_t)0x11)
#define RegIrqFlags                    ((__uint8_t)0x12)
#define RegRxNbBytes                   ((__uint8_t)0x13)
#define RegRxHeaderCntValueMsb         ((__uint8_t)0x14)
#define RegRxHeaderCntValueLsb         ((__uint8_t)0x15)
#define RegRxPacketCntValueMsb         ((__uint8_t)0x16)
#define RegRxPacketCntValueLsb         ((__uint8_t)0x17)
#define RegModemStat                   ((__uint8_t)0x18)
#define RegPktSnrValue                 ((__uint8_t)0x19)
#define RegPktRssiValue                ((__uint8_t)0x1A)
#define RegRssiValue                   ((__uint8_t)0x1B)
#define RegHopChannel                  ((__uint8_t)0x1C)
#define RegModemConfig1                ((__uint8_t)0x1D)
#define RegModemConfig2                ((__uint8_t)0x1E)
#define RegSymbTimeoutLsb              ((__uint8_t)0x1F)
#define RegPreambleMsb                 ((__uint8_t)0x20)
#define RegPreambleLsb                 ((__uint8_t)0x21)
#define RegPayloadLength               ((__uint8_t)0x22)
#define RegMaxPayloadLength            ((__uint8_t)0x23)
#define RegHopPeriod                   ((__uint8_t)0x24)
#define RegFifoRxByteAddr              ((__uint8_t)0x25)
#define RegModemConfig3                ((__uint8_t)0x26)
#define RegFeiMsb                      ((__uint8_t)0x28)
#define RegFeiMid                      ((__uint8_t)0x29)
#define RegFeiLsb                      ((__uint8_t)0x2A)
#define RegRssiWideband                ((__uint8_t)0x2C)
#define RegIfFreq1                     ((__uint8_t)0x2F)
#define RegIfFreq2                     ((__uint8_t)0x30)
#define RegDetectOptimize              ((__uint8_t)0x31)
#define RegInvertIQ                    ((__uint8_t)0x33)
#define RegHighBwOptimize1             ((__uint8_t)0x36)
#define RegDetectionThreshold          ((__uint8_t)0x37)
#define RegSyncWord                    ((__uint8_t)0x39)
#define RegHighBwOptimize2             ((__uint8_t)0x3A)
#define RegInvertIQ2                   ((__uint8_t)0x3B)
#define RegDioMapping1                 ((__uint8_t)0x40)
#define RegDioMapping2                 ((__uint8_t)0x41)
#define RegVersion                     ((__uint8_t)0x42)
#define RegTcxo                        ((__uint8_t)0x4B)
#define RegPaDac                       ((__uint8_t)0x4D)
#define RegFormerTemp                  ((__uint8_t)0x5B)
#define RegAgcRef                      ((__uint8_t)0x61)
#define RegAgcThresh1                  ((__uint8_t)0x62)
#define RegAgcThresh2                  ((__uint8_t)0x63)
#define RegAgcThresh3                  ((__uint8_t)0x64)
#define RegPll                         ((__uint8_t)0x70)


#endif